# 使用github支持的主题
# theme: jekyll-theme-slate

# 使用github托管的其他主题
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: foty
  tagline: hello world
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/head.png"
  html_lang: "en"
  condensed_mobile:
    - home
    - page
    - post

  social_links:
    github: lxx
    linkedIn:  # format: locale/us ername