# 使用github支持的主题
# theme: jekyll-theme-slate

# 使用github托管的其他主题
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: 职业法师赵得柱
  tagline: hello world !
  date_format: "%b %-d, %Y"

  social_links:
    github: foty

  search: true

  dark_mode: true  #黑暗模式

  portfolio_image: "assets/head.png" #头像

  show_excerpts: true

  sitemap: true

  html_lang: "en"

  condensed_mobile:
    #- home
    - page
    - post

#  navigation:
#    - title: My Work
#      url: "/my-work"
#    - title: Resume
#      url: "/resume"
