# 使用github支持的主题
# theme: jekyll-theme-slate

# 使用github托管的其他主题
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: lxx
    github: lxx
    linkedIn:  # format: locale/username